MODEL:
  SSDS: ssd_lite
  NETS: mobilenet_v2_torchvision
  IMAGE_SIZE: [640, 360]
  NUM_CLASSES: 14
  FEATURE_LAYER: [[11, 17, 'S', 'S', 'S', 'S'], [96, 320, 512, 256, 256, 128]]
  STEPS: [[16, 16], [32, 32], [64, 64], [100, 100], [150, 150], [300, 300]]
  SIZES: [[45, 45], [90, 90], [135, 135], [180, 180], [225, 225], [270, 270]]
  ASPECT_RATIOS: [[1, 2, 3], [1, 2, 3], [1, 2, 3], [1, 2, 3], [1, 2], [1, 2]]

TRAIN:
  MAX_EPOCHS: 100
  CHECKPOINTS_EPOCHS: 5
  BATCH_SIZE: 32
  TRAINABLE_SCOPE: 'base,norm,extras,loc,conf'
  RESUME_SCOPE: 'base,norm,extras,loc,conf'
  OPTIMIZER:
    OPTIMIZER: sgd
    LEARNING_RATE: 0.001
    MOMENTUM: 0.9
    WEIGHT_DECAY: 0.0001
  LR_SCHEDULER:
    SCHEDULER: SGDR
    WARM_UP_EPOCHS: 100

TEST:
  BATCH_SIZE: 64
  TEST_SCOPE: [285, 300]

MATCHER:
  MATCHED_THRESHOLD: 0.6
  UNMATCHED_THRESHOLD: 0.4
  NEGPOS_RATIO: 3

POST_PROCESS:
  SCORE_THRESHOLD: 0.01
  IOU_THRESHOLD: 0.6
  MAX_DETECTIONS: 100

DATASET:
  DATASET: 'voc'
  DATASET_DIR: './data/custom'
  TRAIN_SETS: [['custom','train']]
  TEST_SETS:  [['custom', 'val']]
  PROB: 0.6

EXP_DIR: './experiments/exp'
LOG_DIR: './experiments/log'
RESUME_CHECKPOINT: './experiments/models/mobilenet_v2_ssd_lite_voc.pth'
PHASE: ['train']